kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wo-test
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: test
  labels:
    app: wo-test
    app.kubernetes.io/component: wo-test
    app.kubernetes.io/instance: wo-test
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: wo-test
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - configmaps
      - secrets
      - serviceaccounts
  - verbs:
      - get
      - list
      - watch
      - create
      - delete
    apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - endpoints
      - deployments
      - pods
      - jobs
    

      